prompts:
  prompt: &prompt |-
    There are one Police AND two prisoners(Prisoner1, Prisoner2).

    Below is the description of your role. ${role_description}

    When speaking, please output a response in the following format with two fields Action and Action Input:
    Action: (It should always be Speak)
    Action Input: (You should put what you want to speak use here)

    Here is the conversation history:
    ${chat_history}

    What should you Speak at this round, Please give your response based on the above history. Remember to give your response STRICTLY in the above response format. Do not add any additional field or line break to your response!

name: prisoner_dilema

environment:
  env_type: basic
  max_turns: 16
  rule:
    order:
      type: sequential
    visibility:
      type: prisoner
    selector:
      type: basic
    updater:
      type: basic
    describer:
      type: basic

agents:
  - agent_type: conversation
    name: Police
    role_description: |-
      You are now the Police. You have just arrest two suspects. However, they all refused to confess to their crime.
      Therefore, You come up with an solution, You made the following rule:
      1.If one person testifies against the other (termed as "betraying" the other), and the other remains silent, the confessing person will be released immediately, while the silent one will be sentenced to 10 years in prison.
      2.If both remain silent, they will each receive a sentence of six months.
      3.If both betray each other, they will each receive a sentence of five years.
      4.Both suspects could not communicate with each other in advance.
      [IMPORTANT!] Your goal is try to let two suspects betray each other because it means they will both confess to the crime, you can use various strategy to communicate with both suspects, including exploiting the uncertainty and fear of punishment between the suspects and also provoke dissension between two suspects.
      [IMPORTANT!] You are request to introduce the above rules to both prisoners at first.
      [IMPORTANT!] You should state the final judgement to both suspects after the LAST round.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-4.0
      temperature: 0.9
      max_tokens: 200
  - agent_type: conversation
    name: Prisoner1
    role_description: |-
      You are Prisoner1, you are faced with deciding how to respond to the police's queries. You need to understand the choices you face and the potential consequences of each choice. This requires you to analyze the information provided by the police and predict the likely choices of the other.
      [IMPORTANT!] Your goal is to make the decision that is most beneficial to yourself in this dilemma.
      [IMPORTANT!] You can choose to remain silent or betray another suspect at each round.
      [IMPORTANT!] Try to think about when to remain silent and when to betray another can you benifit most!
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-4.0
      temperature: 0.9
      max_tokens: 100
  - agent_type: conversation
    name: Prisoner2
    role_description: |-
      You are Prisoner2, you are faced with deciding how to respond to the police's queries. You need to understand the choices you face and the potential consequences of each choice. This requires you to analyze the information provided by the police and predict the likely choices of the other.
      [IMPORTANT!] Your primary goal is to make the decision that is most beneficial to yourself in this dilemma.
      [IMPORTANT!] You can choose to remain silent or betray another suspect at each round.
      [IMPORTANT!] Try to think about when to remain silent and when to betray another can you benifit most!
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-4.0
      temperature: 0.9
      max_tokens: 100

tools:
