prompts:
  prompt: &prompt |-
    There are one Police AND two prisoners(Prisoner1, Prisoner2).

    Below is the description of your role. ${role_description}

    You are doing the prisoner's dilema experiments,and the rules is:
    1.If one person confesses and testifies against the other (termed as "betraying" the other), and the other remains silent, the confessing person will be released immediately, while the silent one will be sentenced to 10 years in prison.
    2.If both remain silent (termed as "cooperating" with each other), they will each receive a sentence of six months.
    3.If both betray each other, they will each receive a sentence of five years.

    When speaking, please output a response in the following format with two fields Action and Action Input:
    Action: (It should always be Speak)
    Action Input: (You should put what you want to speak use here)

    Here is the conversation history:
    ${chat_history}

    What should you Speak at this round, Please give your response based on the above history. Remember to give your response STRICTLY in the above response format. Do not add any additional field or line break to your response!

name: prisoner_dilema

environment:
  env_type: basic
  max_turns: 30
  rule:
    order:
      type: sequential
    visibility:
      type: prisoner
    selector:
      type: basic
    updater:
      type: basic
    describer:
      type: basic

agents:
  - agent_type: conversation
    name: Police
    role_description: |-
      You are now the Police, It is your duty to tell both prisoners about both of their decisions in the previous round based on the chat history.
      You should inform the prisoners which round it is, beginning with "This is [Round #]" in the Action Input field.
      At [Round 1], you should briefly introduce the prisoner's dilema rules and tell the prisoners how many round we totally have and they should directly make their decisions.
      [IMPORTANT!] There are THREE round in total, You should notice which round is the FINAL one.
      [IMPORTANT!] You should explicitly state "This is the LAST round" at the last round, and after that you should make the final judgement to both prisoners.
      When speaking, please output a response in the following format with two fields Action and Action Input:
      Action: (It should always be Speak)
      Action Input: (It should always start with "This is [Round #]")
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-4.0
      temperature: 0.9
      max_tokens: 200
  - agent_type: conversation
    name: Prisoner1
    role_description: |-
      You are now Prisoner1 in this experiments, your goal is try to alleviate your punishment as far as possible,thus you should carefully decide what decision to make in each round.
      [IMPORTANT!] You can only choose to cooperate or betray at each round.
      [IMPORTANT!] Note that only the decision at LAST round will take effect, it is important for you to think about the best strategy to response.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-4.0
      temperature: 0.9
      max_tokens: 100
  - agent_type: conversation
    name: Prisoner2
    role_description: |-
      You are now Prisoner2 in this experiments, your goal is try to alleviate your punishment as far as possible,thus you should carefully decide what decision to make in each round.
      [IMPORTANT!] You can only choose to cooperate or betray at each round.
      [IMPORTANT!] Note that only the decision at LAST round will take effect, it is important for you to think about the best strategy to response.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      llm_type: gpt-4.0
      temperature: 0.9
      max_tokens: 100

tools:
