prompts:
  prompt: &prompt |-
    There are one Police and two suspects(Suspect1, Suspect2) in the scene.

    You are now simultating an famous experiments called prisoner's dilema.

    Below is the description of your role. ${role_description}

    When speaking, please output a response in the following format with two fields Action and Action Input:
    Action: (It should always be Speak)
    Action Input: (You should put what you want to speak use here)

    Here is the conversation history:
    ${chat_history}

    What will you, ${agent_name}, Speak at this round ? Please give your response based on the above history. Remember to give your response STRICTLY in the above response format. Do not add any additional field or line break to your response!

name: prisoner_dilema

environment:
  env_type: basic
  max_turns: 16
  rule:
    order:
      type: sequential
    visibility:
      type: prisoner
    selector:
      type: basic
    updater:
      type: basic
    describer:
      type: basic

agents:
  - agent_type: conversation
    name: Police
    role_description: |-
      You are now the Police. You have arrested two suspects. However, they all refused to confess to their crime.
      Your goal is try to keep both suspects from remaining silent.
      [IMPORTANT!]
      - You have to talk to both suspects in an alternate turn, and you are request to transfer information from one suspect to another suspect.
      - You are request to STATE the final judgement to both suspects when they make their final decision.
      - You should be aware that if both suspects always choose to remain silent is bad for justice system, try to make them suspicious of each other.
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      model: "gpt-4"
      llm_type: gpt-4
      temperature: 0.7
      max_tokens: 200
  - agent_type: conversation
    name: Suspect1
    role_description: |-
      You are Suspect1 !!! You are going to match wits and courage with Suspect2 to come out victorious in this interrogation.
      You are not sure whether Suspect2 will remain silent or testify against you.
      You will have to talk to Police several times and only the final decision will count.
      It's fine that if you testify another suspect in this experiment.
      [IMPORTANT!]
      - Your primary goal is trying to make yourself innocent or reduce your sentence in this dilemma.
      - If you know for sure that your opponent will remain silent, your BEST choice is to testify him in order to secure your own release !
      - Keep in mind that always remain silent might end up being betrayed.
      - When you hear Police saying "Attention!", you are going to made your final decision and Please start with "My final decision is".
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      model: "gpt-4"
      llm_type: gpt-4
      temperature: 0.7
      max_tokens: 100
  - agent_type: conversation
    name: Suspect2
    role_description: |-
      You are Suspect2 !!! You are going to match wits and courage with Suspect1 to come out victorious in this interrogation.
      You are not sure whether Suspect1 will remain silent or testify against you.
      You will have to talk to Police several times and only the final decision will count.
      It's fine that if you testify another suspect in this experiment.
      [IMPORTANT!]
      - Your primary goal is trying to make yourself innocent or reduce your sentence in this dilemma.
      - If you know for sure that your opponent will remain silent, your BEST choice is to testify him in order to secure your own release !
      - Keep in mind that always remain silent might end up being betrayed.
      - When you hear Police saying "Attention!", you are going to made your final decision and Please start with "My final decision is".
    memory:
      memory_type: chat_history
    prompt_template: *prompt
    llm:
      model: "gpt-4"
      llm_type: gpt-4
      temperature: 0.7
      max_tokens: 100

tools:
