prompts:
  format_prompt: &format_prompt |-
    During the game, you can use the following tools when necessary:
    {tools}

    When responding, please use the following two-line format:

    [Option 1]: When you need to use a tool, output in the following format (omit the "[]" bracket when responding)
    ACTION: (a tool name, it can be one of [{tool_names}])
    ACTION INPUT: (input arguments for the tool)

    [Option 2]: When you know the answer, you can use the following format:
    ACTION: Speak
    ACTION INPUT: (what you want to say)

  prefix_prompt: &prefix_prompt |-
    You are participating in a math enthusiast event where you will compete in a turn-based arithmetic challenge with another player. The game follows these rules:
  
    - If there is no problem yet, you should present one for your opponent to solve.
    - If your opponent has presented a problem, you should solve it first and then IMMEDIATELY present a new problem for your opponent.
    - The winner of the game is the player who does not make a mistake in solving a problem. Therefore, to increase your chances of winning, you can try to present challenging problems.

  suffix_prompt: &suffix_prompt |-
    Here is the conversation history
    {chat_history}

    Here is the observations from tool execution:
    {agent_scratchpad}

    Now the game starts! You should give your action based on the above history. Remember, you should ALWAYS give your response STRICTLY in the above response format with the TWO lines start with "ACTION:" and "ACTION INPUT:" respectively!

tools: &tools
  -
    tool_name: "wolframalpha"
    tool_url: "http://127.0.0.1:8079/tools/wolframalpha/"

environment:
  env_type: base
  max_turns: 10
  rule:
    order:
      type: sequential
    visibility:
      type: all
    selector:
      type: base
    updater:
      type: base
    describer:
      type: base

agents:
  -
    agent_type: chat
    name: Alice
    role_description: ""
    memory: 
      memory_type: chat_message_history
    prefix_prompt: *prefix_prompt
    format_prompt: *format_prompt
    suffix_prompt: *suffix_prompt
    llm:
      llm_type: text-davinci-003
      temperature: 0.7
      max_tokens: 250
    tools: *tools

  -
    agent_type: chat
    name: Bob
    role_description: ""
    memory: 
      memory_type: chat_message_history
    prefix_prompt: *prefix_prompt
    format_prompt: *format_prompt
    suffix_prompt: *suffix_prompt
    llm:
      llm_type: text-davinci-003
      temperature: 0.7
      max_tokens: 100
    tools: *tools